import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Cover } from '@/components/home/cover'
import { ServiceH } from '@/components/home/service'
import { GalleryH } from '@/components/home/gallery'
import { ArticleH } from '@/components/home/artical'
import { Footer } from '@/components/general/footer'
import { Navbar } from '@/components/general/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <section id='home'/>
        <Cover/>
        <section id='service'/>
        <ServiceH/>
        <section id='gallery'/>
        <GalleryH/>
        <section id='aboutus'/>
        <ArticleH/>
        <section id='contact'/>
    </>
  )
}
